# Web ContextRootPath and PortNumber Settings
# server.servlet.context-path=/enjoytrip
server:
  port: 80

# DataBase Settings : hikariCP : https://github.com/brettwooldridge/HikariCP
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enjoytrip?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    hikari: 
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ssafy
      password: ssafy
      pool-name: Hikari Connection Pool
      
# hikariCP property setting
      maximum-pool-size: 50
      minimum-idle: 50
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      
# swagger setting >> Failed to start bean 'documentationPluginsBootstrapper'; error
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# File Upload size Setting
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
      
#MyBatis Setting
mybatis:
  type-aliases-package: com.ssafy.trip.*.model
  mapper-locations: classpath:mappers/*.xml

#log level Setting
logging:
  level:
    root: info
    com:
      ssafy: debug

# file upload path : window
file:
  path:
    upload-default: C:/board/upload/
    upload-images: C:/board/upload/imageUpload
    upload-files: C:/board/upload/fileUpload/

# JWT setting
jwt: 
  salt: ssafy-screte-key
#1 hour (millis)
  access-token:
    expiretime: 3600000
# 30 days (millis)
  refresh-token: 
    expiretime: 2592000000